from pathlib import Path
from datetime import datetime


def save_markdown_report(
    task: str,
    profile: dict,
    stats: dict,
    interpretation: str,
    validation: dict,
    project_name: str,
    run_name: str,
) -> Path:
    """Save markdown report without overwriting previous versions."""

    output_dir = Path(f"projects/{project_name}/outputs/reports")
    output_dir.mkdir(parents=True, exist_ok=True)

    base_path = output_dir / f"{run_name}.md"

    if not base_path.exists():
        output_path = base_path
    else:
        version = 2

        while True:
            versioned_path = output_dir / f"{run_name}_v{version}.md"

            if not versioned_path.exists():
                output_path = versioned_path
                break

            version += 1

    report = f"""# Analysis Report

Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Task

{task}

## Dataset Overview

- Rows: {profile.get("row_count")}
- Columns: {profile.get("column_count")}
- Duplicate rows: {profile.get("duplicate_rows")}
- Numeric columns: {profile.get("numeric_columns")}
- Categorical columns: {profile.get("categorical_columns")}

## Missing Values

{profile.get("missing_values")}

## Method Used

Descriptive statistics were computed using column-type classification. Variables were separated into continuous numeric, binary, low-cardinality numeric, categorical, and technical pipeline columns.

Technical columns such as `_clean`, `_invalid_flag`, and `_missing_flag` are excluded from primary analytical interpretation and reserved for validation notes.

## Results

{stats}

## Interpretation

{interpretation}

## Validation

Status: `{validation.get("status")}`

Warnings:
{validation.get("warnings", [])}

Issues:
{validation.get("issues", [])}

## Governance Note

This report was generated by StatsAgent as an AI-assisted analytical output.

The report is intended for analytical support and validation purposes. Outputs should be reviewed by a human analyst before operational, financial, customer-impacting, or business-critical use.

Raw row-level data is not required for interpretation; the LLM interpretation layer should receive compact statistical summaries where possible.
"""

    output_path.write_text(report, encoding="utf-8")

    return output_path